### PR TITLE
Various Optimizations

### PR DESCRIPTION
**Pull request by kinsi55**
- Pretty much rewrote Animation loading to be much more efficient and cut down on unnecessary slowdowns resulting in an overall 2-3x speed increase depending on anim size
- Increased the Atlas size limit to 4096 instead of 2048 so that bigger / longer animations dont get downscaled super hard. I'm thinking every GPU that can run BS well can do 4096 Atlasses too
- Added centralized caching for Sprites / Textures applied with the "#<name>" thingy
- Fixed various issues with Sliders (OnChange is called even when the value did not change, displayed value only popping in late, or possibly not at all when enabled late by something like a Tab)
- Switched various String comparisons to Ordinal (Faster)
- Changed First/FirstOrDefault with predicates to .Where().First-/OrDefault which is faster because Linq

### CODE REVIEW

**Comment by Auros** [comment]
The main thing I don't like about this PR is the inconsistency of code style and the mixing of tabs and spaces *everywhere*. You should try to keep the code style consistent.

**Comment by kinsi55** [comment]
Well, I guess my IDE settings use Tabs and others use Space. Monkey should add an Editorconfig.

**Comment by Auros** [comment]
Still, you should make an effort to keep consistency when contributing to another project. Although I'm not monkey, I probably wouldn't accept this PR just on the grounds of the severe discrepancy of style over 23 changed files. Visual Studio has something called Adaptive Formatting which is enabled by default which prevents these kinds of things.

**Comment by kinsi55** [comment]
I have not disabled such a thing, and when typing code, it was always my style settings ( brace on same line, no space etc ), so I made manual effort to clean up all of that, but didnt think about the whitespace.

Edit: Yep, its on indeed
devenv_2022-04-26_16-54-42

**Comment by Auros** [comment]
Strange. In that case, the only other inconsistency is the mix of if, else, for, foreach, async etc etc keywords without spaces between their conditional parentheses.

**Comment by kinsi55** [comment]
But yeah, for someone who has the right editor settings it should be easy enough to select / autoformat these files and include an editorconfig so people like me who prefer a more condensed code style can contribute too without gettin a headache :P (VS can export your editor settings as an editorconfig in the options)

**Comment by Auros** [comment]
In that case, I played with your build in modders-only for an hour and didn't notice anything wrong.

**Pull request merged**
