### PR TITLE
Added callback to SetImage

### PR DESCRIPTION
**Pull request by Taffeeko**
I am back once again to make changes no one will use on a single silly method which I barely understand

Code goes headless and making things asynchronous is hard so I've put in a call back

### CODE REVIEW

**Comment by kinsi55** [comment]
What is the point of this? SetImage() is synchronous

Calling your callback (yourself) below the SetImage() call has the same effect

**Comment by Taffeeko** [comment]
> Code goes headless and making things asynchronous is hard so I've put in a call back

Probably caused by the downscaling and/or GetData call

**Comment by kinsi55** [comment]
Oh right because GetData can do web sources too.

Well, in that case you forgot the callback in the first GetData() call

That being said, whats your usecase?

**Comment by Taffeeko** [comment]
I just need to know when the image is loaded, adding a call back onto the method which handles loading in the images seemed like the best approach since that method also goes headless for whatever reason

**Pull request merged**
